version: '3.8'

services:
  db:
    image: postgres:14
    container_name: inhibitor-detector-db
    environment:
      POSTGRES_USER: user          # Usuario predeterminado
      POSTGRES_PASSWORD: 123123123 # Contraseña predeterminada
      POSTGRES_DB: inhibitor_detector  # Nombre de la base de datos predeterminada
    ports:
      - "5432:5432"  # Exponer el puerto de la base de datos
    volumes:
      - ./api/persistence/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app_network
    restart: always
    expose: 
      - "5432"

  app:
    image: tataabancens/detector-api:1.0.4  # Usa la imagen que subiste a Docker Hub
    container_name: inhibitor-detector-api
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/inhibitor_detector  # Conexión a la base de datos usando el nombre del servicio
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=123123123
      - SERVER_PORT=8001
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8001:8001"  # Exponer el puerto de la aplicación en el host
    networks:
      - app_network
    restart: always

  frontend:
    image: tataabancens/detector-frontend:1.0.4  # Usa la imagen que subiste a Docker Hub
    container_name: inhibitor-detector-frontend
    depends_on:
      - app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
